namespace: default

image: img234/kafka-image-consumer:0.1.4

port: 8000

appId: "kafka-image-consumer-001"

replicaCount: 0

nodeType: "server"

resources:
  limits:
    cpu: "500m"
    memory: "1024Mi"
  requests:
    cpu: "250m"
    memory: "512Mi"

serviceType: ClusterIP
