namespace: default

image: img234/kafka-consumer-model:0.1.5

port: 8000

appId: "kafka-consumer-model-001"

replicaCount: 0

nodeType: "server"

resources:
  limits:
    cpu: "500m"
    memory: "1200Mi"
    nvidia.com/gpu: 1
  requests:
    cpu: "250m"
    memory: "512Mi"
    nvidia.com/gpu: 1

serviceType: ClusterIP
