apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    namespace: {{ .Values.namespace }}
spec:
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      namespace: {{ .Values.namespace }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        namespace: {{ .Values.namespace }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ $.Values.port }}
          env:
            - name: CONFIG_HOST
              value: "grpc-config-server"
            - name: CONFIG_PORT
              value: "21001"
            - name: APP_ID
              value: "{{ $.Values.appId }}"
            - name: TZ
              value: Asia/Seoul
          resources: {{- toYaml $.Values.resources | nindent 12 }}
      restartPolicy: Always
