namespace: default

image: img234/kafka-changestream-producer:0.1.1

port: 8000

appId: "kafka-changestream-producer-001"

replicaCount: 0

nodeType: "server"

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

serviceType: ClusterIP
